name = "tideswell-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[triggers]
crons = ["*/30 * * * *"] # every 30 minutes

[vars]
# Feature flags per site; extend as needed
SITES = "soccerdealsdaily,techsaverdaily"
